services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ai-assistant-api

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DbConnection: "Host=postgres;Port=5432;Database=ai_assistant;Username=postgres;Password=${DB_PASSWORD}"

      Jwt__Key: "${JWT_KEY}"
      Jwt__Issuer: "${JWT_ISSUER}"
      Jwt__Audience: "${JWT_AUDIENCE}"

      OpenAI__apiKey: "${OPENAI_API_KEY}"

      OpenWeather__weatherApi: "${OPENWEATHER_API_KEY}"

    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres:16

    container_name: ai-assistant-postgres

    environment:
      POSTGRES_DB: ai_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ai_assistant"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: